spring:
  application:
    name: document
  datasource:
    url: jdbc:postgresql://localhost:5432/document_report
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: 28112002akn@gmail.com
    password: fkmeodoueagkcrri
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true