spring:
  application:
    name: document
  datasource:
    url: jdbc:postgresql://localhost:5432/document_report
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: 28112002akn@gmail.com
    password: fkmeodoueagkcrri
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 1MB

minio:
  url: http://localhost:9000
  accessKey: joe
  secretKey: joecessler
  bucketName: document